[workspace]
changelog_update = true
git_release_enable = true
pr_labels = ["release"]
publish = false
semver_check = false
dependencies_update = false

[changelog]
header = """# CHANGELOG
All notable changes to this project will be documented in this file.

## [Unreleased]
"""
trim = true
