name: build
run-name: build ${{ github.ref_name }} by ${{ github.actor }}
on: [push]
jobs:
  cargo-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo build
    
