name: build
run-name: build ${{ github.ref_name }} by ${{ github.actor }}
on: [push]
jobs:
  cargo-build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: install rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: build
        run: make local-build

