name: release
run-name: release ${{ github.ref_name }}
on:
  push:
    tags:
      - '**[0-9]+.[0-9]+.[0-9]+*'

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      release_title: "${{ steps.release_text.outputs.release_title }}"
      release_notes: "${{ steps.release_text.outputs.release_notes }}"
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: install rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: intall git-cliff
        uses: baptiste0928/cargo-install@v3
        with:
          crate: git-cliff

      - name: verify changelog status
        run: |
          make check-changelog

      - name: extract changelog for version
        id: release_text
        run: |
          RELEASE_TITLE="${{ github.ref_name }}"
          RELEASE_NOTES=$(git-cliff --current)
          echo "release_title=$RELEASE_TITLE" >> "$GITHUB_OUTPUT"
          echo "release_notes<<EOF" >> "$GITHUB_OUTPUT"
          echo "$RELEASE_NOTES" >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"

# build matrix
  build:
    needs: [ setup ]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config:
          - target: "x86_64-unknown-linux-gnu"
          - target: "aarch64-unknown-linux-gnu"
    steps:
      - name: install rustup target
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: intall cross
        uses: baptiste0928/cargo-install@v3
        with:
          crate: cross

      - name: checkout
        uses: actions/checkout@v4

      - name: build
        run: |
          make release-build TARGET=${{ matrix.config.target }}
          zip feed2imap_${{ matrix.config.target }}.zip target/${{ matrix.config.target }}/dist/feed2imap

      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: "feed2imap_${{ matrix.config.target }}.zip"
          path: "feed2imap_${{ matrix.config.target }}.zip"
          if-no-files-found: error
          compression-level: 9
          
# upload build result to release announcement
  announce:
    needs: [ setup, build ]
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts/
          pattern: "feed2imap_*.zip"
          merge-multiple: true
      - name: create release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          draft: false
          tag: "${{ github.ref_name }}"
          name: "${{ needs.setup.outputs.release_title }}"
          body: "${{ needs.setup.outputs.release_notes }}"
          artifacts: "artifacts/*"
        

# extract changelog part for release announcement
